---
abstract: 'draw pattern by cellular automata'
author:
  - 'Herbert Breunung <lichtkind@cpan.org>'
build_requires:
  Test::More: '1.3'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-GUI-Cellgraph
no_index:
  directory:
    - t
  namespace:
    - App::GUI::Cellgraph
provides:
  App::GUI::Cellgraph:
    file: lib/App/GUI/Cellgraph.pm
    version: 0.6_91
requires:
  File::HomeDir: '1'
  File::Spec: '3'
  FindBin: '1'
  Graphics::Toolkit::Color: '1.71'
  Wx: '0.9'
  perl: v5.12.0
resources:
  repository: git://github.com/lichtkind/App-GUI-Cellgraph.git
version: 0.6_91
x_generated_by_perl: v5.34.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: GPL-3.0-only
